jenkins:
  systemMessage: "All configuration for this controller is done as code (JCasC)"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}
        properties:
        - timezone:
            timeZoneName: "Europe/London"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  scriptApproval:
    approvedSignatures:
      - "field hudson.model.Run project"
      - "method hudson.model.AbstractItem setDescription java.lang.String"
      - "method hudson.model.AbstractItem setDisplayName java.lang.String"
      - "method hudson.model.Computer setTemporarilyOffline boolean hudson.slaves.OfflineCause"
      - "method hudson.model.Node toComputer"
      - "method io.jenkins.plugins.casc.ConfigurationAsCode configureWith java.util.List"
      - "method jenkins.model.Jenkins getNode java.lang.String"
      - "method org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper getRawBuild"
      - "new hudson.slaves.OfflineCause$ByCLI java.lang.String"
      - "staticField java.lang.System err"
      - "staticMethod io.jenkins.plugins.casc.ConfigurationAsCode get"
      - "staticMethod io.jenkins.plugins.casc.yaml.YamlSource of java.lang.String"
      - "staticMethod jenkins.model.Jenkins getInstance"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods replaceAll java.lang.String\
        \ java.util.regex.Pattern java.lang.String"

unclassified:
  location:
    url: http://jenkins.home:8080
jobs:
    - script: >
        pipelineJob("Seed-Job-Or-Update-Pipelines") {
        definition {
            cpsScm {
                lightweight(true)
                scriptPath "Pipelines/Seed-Job-Or-Update-Pipelines/Seed-Job-Or-Update-Pipelines.jenkinsfile"
                scm {
                    git{
                      remote {
                        credentials("jenkins-github-ssh")
                        url("https://github.com/JordanW94/jenkinsCasC.git")
                      }
                      
                      branch("refs/heads/master")
                    }
                }
            }
          }
        }
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "DockerHub"
          password: ${DOCKERHUB_PASSWORD}
          scope: GLOBAL
          username: "jwhitbread"
      - basicSSHUserPrivateKey:
          scope: GLOBAL
          id: jenkins-github-ssh
          username: ${GITHUB_USERNAME}
          description: "Jenkins SSH Key for github"
          privateKeySource:
            directEntry:
              privateKey: ${GITHUB_PRIVATE_KEY}